### PR TITLE
fix(HtmlParser): return null for unclosed script and style tags

### LINKED ISSUE #35: The parser should return null for a non-atomic script or style tag
The new behaviour is causing problems in Postscribe.

See: https://github.com/krux/postscribe/issues/172

### PR DESCRIPTION
**Pull request by sethyates**
In the original version of HtmlParser embedded in postscribe, we would return null for script and
style tokens.  This behaviour appears to have changed in the extraction and we should revert to that
earlier behaviour since it makes no sense to return just the start tag for script and style.

Fixes #35

### CODE REVIEW

File: src/HtmlParser.js [hunk 1]
```diff
@@ -93,17 +97,30 @@ export default class HtmlParser {
       if (detect.hasOwnProperty(type)) {
         if (detect[type].test(this.stream)) {
           const token = streamReaders[type](this.stream);
+
           if (token) {
-            token.text = this.stream.substr(0, token.length);
-            return token;
+            if (token.type == 'startTag' &&
+                (/script|style/i).test(token.tagName)) {
```
Comment (jnewman) [inline src/HtmlParser.js]: This was actually more than these two https://github.com/krux/postscribe/blob/1.4.0/htmlParser/htmlParser.js#L76

**Comment by jnewman** [comment]
Lgtm aside from the one note

File: src/HtmlParser.js [hunk 2]
```diff
@@ -93,17 +97,30 @@ export default class HtmlParser {
       if (detect.hasOwnProperty(type)) {
         if (detect[type].test(this.stream)) {
           const token = streamReaders[type](this.stream);
+
           if (token) {
-            token.text = this.stream.substr(0, token.length);
-            return token;
+            if (token.type == 'startTag' &&
```
Comment (jnewman) [inline src/HtmlParser.js]: Nit - `===`

**Comment by jnewman** [comment]
This test: https://github.com/krux/postscribe/blob/master/test/fixtures/write-comparisons.js#L17-L22 starts failing with the new changes. I'll try to reproduce in prescribe

File: src/HtmlParser.js (hunk 1 above)
Comment (sethyates) [inline src/HtmlParser.js]: Yeah I know. We have that same code in HtmlParser and I considered those other options as well but none of the other ones are like script and style in that the others contain HTML within them and so could be parsed.

**Comment by jnewman** [comment]
I think the test was passing before, but only b/c of the autoself closing that we didn't want.

**Comment by jnewman** [comment]
👍 aside from nits
